### ISSUE TITLE
How many accounts should campus safety have?

### ISSUE THREAD

**Issue by jmankhan** [MCEMS/api#1]

**Comment by victorlora** [comment]
Probably one master admin and a way to expand?

**Comment by benburwell** [comment]
From an accountability perspective, I'd love for each dispatcher to have their own credentials, but this probably isn't practical. My guess is we'll end up just creating a "Campus Safety Dispatcher" profile that they all use. This would be something to have Eli talk to MCPD about.

**Comment by benburwell** [comment]
@EliRuss, do you have an answer for this? I'd like to close this if we can. Thanks!

**Comment by EliRuss** [comment]
My understanding is that one Dispatcher account is sufficient (and simpler is better). Let's go with that for now, and I will follow up to make it official.

@benburwell, as we just discussed, please create a simpler login password. Previous login was -
Username: mcdcs
Password: otdumjar

**Comment by benburwell** [comment]
This issue has been resolved offline
