### ISSUE TITLE
Create JavaScript client

### ISSUE THREAD

**Issue by benburwell** [MCEMS/api#6]
This will be loaded from `/client/v1.js`. It would be nice if it was generated at least somewhat automatically based on backend stuff. Ideally, it would be written in CoffeeScript and compiled/minified as part of the build. The server should be able to respond to a request for this file very quickly, let's make sure the HTTP headers have a good cache policy.

**Comment by benburwell** [comment]
Would you be able to work on this over the weekend? I'd like to have a rough implementation of the dispatch console done by the end of next week.

Initially, I wouldn't worry about compiling/minifying. Just use Hapi to [serve a static file](http://hapijs.com/tutorials/serving-files). All it needs to do is use the `POST /auth/key` route to get an access token, probably use Javascript's `setInterval()` function to refresh this token when necessary, and use that token to `POST` to the yet-to-be-created route `/api/v1/alert`.

Let me know if you have any questions! Thanks :)

**Comment by jmankhan** [comment]
The work is currently in progress

**Comment by benburwell** [comment]
Great! Feel free to open a PR any time, even if it's a work in progress.

**Comment by benburwell** [comment]
Also check out https://github.com/MCEMS/dispatch/blob/master/static/client.js, I implemented the bare minimum necessary to send alerts. Feel free to build off of this.

That script is just going to be temporary until we have this created that all sites can share.

**Comment by benburwell** [comment]
Closing this for now while investigating Loopback's built-in SDKs. May reopen in the future.
